add missing dependency
fix:
```
[ 50%] Building CXX object CMakeFiles/ros2_control_demo_example_17.dir/hardware/rrbot.cpp.o
In file included from /build/source/example_17/hardware/rrbot.cpp:15:
/build/source/example_17/hardware/include/ros2_control_demo_example_17/rrbot.hpp:59:5: error: 'control_msgs' has not been declared
   59 |     control_msgs::msg::HardwareStatus & msg_template) override;
      |     ^~~~~~~~~~~~
```